# Site settings
title: "Felix Resume"
description: "Felix Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Felix.Hu"
resume_title:                   "iOS Developer/Digital Nomad"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hulj3733@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "Chengdu, Sichuan, China &nbsp;"
display_header_contact_info:    "true"

resume_header_intro: "<p>I'm a professional developer who focuses on iOS. With strong knowledge of Swift, Objective-C, RxSwift, MVVM and POP programming. Also write some HTML/CSS and Node.js, and interested in web3.  &nbsp; <a href=\"https://kk-vv.github.io\" style=\"color: #000 !important;\" >CN</a></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kk-vv"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  # resume_linkedin_url:          ""
  # resume_instagram_url:         ""
  # resume_website_url:           ""
  # resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
